In [2]:
import torch

In [3]:
tensor_1 = torch.tensor([2,4,5])
tensor_1

tensor([2, 4, 5])

In [4]:
tensor_2 = torch.tensor([3,6,1])
tensor_1+tensor_2

tensor([ 5, 10,  6])

In [ ]:
tensor_3 = torch.tensor([[3,6,1],
                         [1,1,1],
                         [3,1,0]])
tensor_4 = torch.tensor([[2,3,0],
                         [2,7,1],
                         [9,1,9]])
tensor_3+tensor_4

tensor([[ 5,  9,  1],
        [ 3,  8,  2],
        [12,  2,  9]])